#!/bin/sh
#
# Usage: extract <file>
# Description: extracts archived files / mounts disk images
# Note: .dmg/hdiutil is macOS-specific.
#
# credit: http://nparikh.org/notes/zshrc.txt
extract () {
    if [ -f "$1" ]; then
        # Set destination to second argument or current directory if not provided
        DEST=${2:-.}
        
        # Create destination directory if it doesn't exist
        mkdir -p "$DEST"
        
        case $1 in
            *.tar.bz2)  tar -jxvf "$1" -C "$DEST"           ;;
            *.tar.gz)   tar -zxvf "$1" -C "$DEST"           ;;
            *.bz2)      bunzip2 -c "$1" > "$DEST/$(basename "$1" .bz2)" ;;
            *.dmg)      hdiutil mount "$1" -mountpoint "$DEST" ;;
            *.gz)       gunzip -c "$1" > "$DEST/$(basename "$1" .gz)" ;;
            *.tar)      tar -xvf "$1" -C "$DEST"            ;;
            *.tbz2)     tar -jxvf "$1" -C "$DEST"           ;;
            *.tgz)      tar -zxvf "$1" -C "$DEST"           ;;
            *.zip)      unzip "$1" -d "$DEST"               ;;
            *.ZIP)      unzip "$1" -d "$DEST"               ;;
            *.pax)      pax -r < "$1" -C "$DEST"            ;;
            *.pax.Z)    uncompress "$1" --stdout | pax -r -C "$DEST" ;;
            *.rar)      unrar x "$1" "$DEST"                ;;
            *.Z)        uncompress -c "$1" > "$DEST/$(basename "$1" .Z)" ;;
            *)          echo "'$1' cannot be extracted/mounted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
